export const otherGames = {
  "Genshin Impact": [
    { name: "Aether", image: "https://ui-avatars.com/api/?name=Aether&background=random" },
    { name: "Lumine", image: "https://ui-avatars.com/api/?name=Lumine&background=random" },
    { name: "Amber", image: "https://ui-avatars.com/api/?name=Amber&background=random" },
    { name: "Barbara", image: "https://ui-avatars.com/api/?name=Barbara&background=random" },
    { name: "Beidou", image: "https://ui-avatars.com/api/?name=Beidou&background=random" },
    { name: "Bennett", image: "https://ui-avatars.com/api/?name=Bennett&background=random" },
    { name: "Chongyun", image: "https://ui-avatars.com/api/?name=Chongyun&background=random" },
    { name: "Diluc", image: "https://ui-avatars.com/api/?name=Diluc&background=random" },
    { name: "Diona", image: "https://ui-avatars.com/api/?name=Diona&background=random" },
    { name: "Eula", image: "https://ui-avatars.com/api/?name=Eula&background=random" },
    { name: "Fischl", image: "https://ui-avatars.com/api/?name=Fischl&background=random" },
    { name: "Ganyu", image: "https://ui-avatars.com/api/?name=Ganyu&background=random" },
    { name: "Hu Tao", image: "https://ui-avatars.com/api/?name=Hu%20Tao&background=random" },
    { name: "Jean", image: "https://ui-avatars.com/api/?name=Jean&background=random" },
    { name: "Kaeya", image: "https://ui-avatars.com/api/?name=Kaeya&background=random" },
    { name: "Klee", image: "https://ui-avatars.com/api/?name=Klee&background=random" },
    { name: "Keqing", image: "https://ui-avatars.com/api/?name=Keqing&background=random" },
    { name: "Lisa", image: "https://ui-avatars.com/api/?name=Lisa&background=random" },
    { name: "Mona", image: "https://ui-avatars.com/api/?name=Mona&background=random" },
    { name: "Ningguang", image: "https://ui-avatars.com/api/?name=Ningguang&background=random" },
    { name: "Noelle", image: "https://ui-avatars.com/api/?name=Noelle&background=random" },
    { name: "Qiqi", image: "https://ui-avatars.com/api/?name=Qiqi&background=random" },
    { name: "Razor", image: "https://ui-avatars.com/api/?name=Razor&background=random" },
    { name: "Rosaria", image: "https://ui-avatars.com/api/?name=Rosaria&background=random" },
    { name: "Sucrose", image: "https://ui-avatars.com/api/?name=Sucrose&background=random" },
    { name: "Tartaglia", image: "https://ui-avatars.com/api/?name=Tartaglia&background=random" },
    { name: "Venti", image: "https://ui-avatars.com/api/?name=Venti&background=random" },
    { name: "Xiangling", image: "https://ui-avatars.com/api/?name=Xiangling&background=random" },
    { name: "Xiao", image: "https://ui-avatars.com/api/?name=Xiao&background=random" },
    { name: "Xingqiu", image: "https://ui-avatars.com/api/?name=Xingqiu&background=random" },
    { name: "Xinyan", image: "https://ui-avatars.com/api/?name=Xinyan&background=random" },
    { name: "Yanfei", image: "https://ui-avatars.com/api/?name=Yanfei&background=random" },
    { name: "Zhongli", image: "https://ui-avatars.com/api/?name=Zhongli&background=random" },
    { name: "Albedo", image: "https://ui-avatars.com/api/?name=Albedo&background=random" },
    { name: "Alice", image: "https://ui-avatars.com/api/?name=Alice&background=random" },
    { name: "Ayaka", image: "https://ui-avatars.com/api/?name=Ayaka&background=random" },
    { name: "Ayato", image: "https://ui-avatars.com/api/?name=Ayato&background=random" },
    { name: "Baizhu", image: "https://ui-avatars.com/api/?name=Baizhu&background=random" },
    { name: "Childe", image: "https://ui-avatars.com/api/?name=Childe&background=random" },
  ],
  "Valorant": [
    { name: "Brimstone", image: "https://ui-avatars.com/api/?name=Brimstone&background=random" },
    { name: "Viper", image: "https://ui-avatars.com/api/?name=Viper&background=random" },
    { name: "Omen", image: "https://ui-avatars.com/api/?name=Omen&background=random" },
    { name: "Killjoy", image: "https://ui-avatars.com/api/?name=Killjoy&background=random" },
    { name: "Cypher", image: "https://ui-avatars.com/api/?name=Cypher&background=random" },
    { name: "Sova", image: "https://ui-avatars.com/api/?name=Sova&background=random" },
    { name: "Sage", image: "https://ui-avatars.com/api/?name=Sage&background=random" },
    { name: "Phoenix", image: "https://ui-avatars.com/api/?name=Phoenix&background=random" },
    { name: "Jett", image: "https://ui-avatars.com/api/?name=Jett&background=random" },
    { name: "Reyna", image: "https://ui-avatars.com/api/?name=Reyna&background=random" },
    { name: "Raze", image: "https://ui-avatars.com/api/?name=Raze&background=random" },
    { name: "Breach", image: "https://ui-avatars.com/api/?name=Breach&background=random" },
    { name: "Skye", image: "https://ui-avatars.com/api/?name=Skye&background=random" },
    { name: "Yoru", image: "https://ui-avatars.com/api/?name=Yoru&background=random" },
    { name: "Astra", image: "https://ui-avatars.com/api/?name=Astra&background=random" },
    { name: "KAY/O", image: "https://ui-avatars.com/api/?name=KAY%2FO&background=random" },
    { name: "Chamber", image: "https://ui-avatars.com/api/?name=Chamber&background=random" },
    { name: "Neon", image: "https://ui-avatars.com/api/?name=Neon&background=random" },
    { name: "Fade", image: "https://ui-avatars.com/api/?name=Fade&background=random" },
    { name: "Fade", image: "https://ui-avatars.com/api/?name=Fade&background=random" },
    { name: "Harbor", image: "https://ui-avatars.com/api/?name=Harbor&background=random" },
    { name: "Gekko", image: "https://ui-avatars.com/api/?name=Gekko&background=random" },
    { name: "Deadlock", image: "https://ui-avatars.com/api/?name=Deadlock&background=random" },
    { name: "Iso", image: "https://ui-avatars.com/api/?name=Iso&background=random" },
    { name: "Clove", image: "https://ui-avatars.com/api/?name=Clove&background=random" },
    { name: "Vyse", image: "https://ui-avatars.com/api/?name=Vyse&background=random" },
  ],
  "League of Legends": [
    { name: "Ahri", image: "https://ui-avatars.com/api/?name=Ahri&background=random" },
    { name: "Akali", image: "https://ui-avatars.com/api/?name=Akali&background=random" },
    { name: "Alistar", image: "https://ui-avatars.com/api/?name=Alistar&background=random" },
    { name: "Amumu", image: "https://ui-avatars.com/api/?name=Amumu&background=random" },
    { name: "Anivia", image: "https://ui-avatars.com/api/?name=Anivia&background=random" },
    { name: "Annie", image: "https://ui-avatars.com/api/?name=Annie&background=random" },
    { name: "Ashe", image: "https://ui-avatars.com/api/?name=Ashe&background=random" },
    { name: "Annie", image: "https://ui-avatars.com/api/?name=Annie&background=random" },
    { name: "Anivia", image: "https://ui-avatars.com/api/?name=Anivia&background=random" },
    { name: "Aphelios", image: "https://ui-avatars.com/api/?name=Aphelios&background=random" },
    { name: "Aatrox", image: "https://ui-avatars.com/api/?name=Aatrox&background=random" },
    { name: "Aurelion Sol", image: "https://ui-avatars.com/api/?name=Aurelion%20Sol&background=random" },
    { name: "Azir", image: "https://ui-avatars.com/api/?name=Azir&background=random" },
    { name: "Bard", image: "https://ui-avatars.com/api/?name=Bard&background=random" },
    { name: "Blitzcrank", image: "https://ui-avatars.com/api/?name=Blitzcrank&background=random" },
    { name: "Brand", image: "https://ui-avatars.com/api/?name=Brand&background=random" },
    { name: "Braum", image: "https://ui-avatars.com/api/?name=Braum&background=random" },
    { name: "Caitlyn", image: "https://ui-avatars.com/api/?name=Caitlyn&background=random" },
    { name: "Camille", image: "https://ui-avatars.com/api/?name=Camille&background=random" },
    { name: "Cassiopeia", image: "https://ui-avatars.com/api/?name=Cassiopeia&background=random" },
    { name: "Cho Gath", image: "https://ui-avatars.com/api/?name=Cho%20Gath&background=random" },
    { name: "Corki", image: "https://ui-avatars.com/api/?name=Corki&background=random" },
    { name: "Darius", image: "https://ui-avatars.com/api/?name=Darius&background=random" },
    { name: "Diana", image: "https://ui-avatars.com/api/?name=Diana&background=random" },
    { name: "Dr. Mundo", image: "https://ui-avatars.com/api/?name=Dr.%20Mundo&background=random" },
    { name: "Draven", image: "https://ui-avatars.com/api/?name=Draven&background=random" },
    { name: "Ekko", image: "https://ui-avatars.com/api/?name=Ekko&background=random" },
    { name: "Elise", image: "https://ui-avatars.com/api/?name=Elise&background=random" },
    { name: "Evelynn", image: "https://ui-avatars.com/api/?name=Evelynn&background=random" },
    { name: "Ezreal", image: "https://ui-avatars.com/api/?name=Ezreal&background=random" },
    { name: "Fiddlesticks", image: "https://ui-avatars.com/api/?name=Fiddlesticks&background=random" },
    { name: "Fiora", image: "https://ui-avatars.com/api/?name=Fiora&background=random" },
    { name: "Fizz", image: "https://ui-avatars.com/api/?name=Fizz&background=random" },
    { name: "Galio", image: "https://ui-avatars.com/api/?name=Galio&background=random" },
    { name: "Gangplank", image: "https://ui-avatars.com/api/?name=Gangplank&background=random" },
    { name: "Garen", image: "https://ui-avatars.com/api/?name=Garen&background=random" },
  ],
  "Overwatch": [
    { name: "Ana", image: "https://ui-avatars.com/api/?name=Ana&background=random" },
    { name: "Ashe", image: "https://ui-avatars.com/api/?name=Ashe&background=random" },
    { name: "Baptiste", image: "https://ui-avatars.com/api/?name=Baptiste&background=random" },
    { name: "Bastion", image: "https://ui-avatars.com/api/?name=Bastion&background=random" },
    { name: "Brigitte", image: "https://ui-avatars.com/api/?name=Brigitte&background=random" },
    { name: "Cassidy", image: "https://ui-avatars.com/api/?name=Cassidy&background=random" },
    { name: "Cassidy", image: "https://ui-avatars.com/api/?name=Cassidy&background=random" },
    { name: "Doomfist", image: "https://ui-avatars.com/api/?name=Doomfist&background=random" },
    { name: "D.Va", image: "https://ui-avatars.com/api/?name=D.Va&background=random" },
    { name: "Echo", image: "https://ui-avatars.com/api/?name=Echo&background=random" },
    { name: "Genji", image: "https://ui-avatars.com/api/?name=Genji&background=random" },
    { name: "Hanzo", image: "https://ui-avatars.com/api/?name=Hanzo&background=random" },
    { name: "Illari", image: "https://ui-avatars.com/api/?name=Illari&background=random" },
    { name: "Junker Queen", image: "https://ui-avatars.com/api/?name=Junker%20Queen&background=random" },
    { name: "Junkrat", image: "https://ui-avatars.com/api/?name=Junkrat&background=random" },
    { name: "Kiriko", image: "https://ui-avatars.com/api/?name=Kiriko&background=random" },
    { name: "Lifeweaver", image: "https://ui-avatars.com/api/?name=Lifeweaver&background=random" },
    { name: "Lucio", image: "https://ui-avatars.com/api/?name=Lucio&background=random" },
    { name: "Mauga", image: "https://ui-avatars.com/api/?name=Mauga&background=random" },
    { name: "Mei", image: "https://ui-avatars.com/api/?name=Mei&background=random" },
    { name: "Mercy", image: "https://ui-avatars.com/api/?name=Mercy&background=random" },
    { name: "Moira", image: "https://ui-avatars.com/api/?name=Moira&background=random" },
    { name: "Orisa", image: "https://ui-avatars.com/api/?name=Orisa&background=random" },
    { name: "Pharah", image: "https://ui-avatars.com/api/?name=Pharah&background=random" },
    { name: "Ramattra", image: "https://ui-avatars.com/api/?name=Ramattra&background=random" },
    { name: "Reaper", image: "https://ui-avatars.com/api/?name=Reaper&background=random" },
    { name: "Reinhardt", image: "https://ui-avatars.com/api/?name=Reinhardt&background=random" },
    { name: "Roadhog", image: "https://ui-avatars.com/api/?name=Roadhog&background=random" },
    { name: "Sigma", image: "https://ui-avatars.com/api/?name=Sigma&background=random" },
    { name: "Sojourn", image: "https://ui-avatars.com/api/?name=Sojourn&background=random" },
    { name: "Soldier: 76", image: "https://ui-avatars.com/api/?name=Soldier%3A%2076&background=random" },
    { name: "Sombra", image: "https://ui-avatars.com/api/?name=Sombra&background=random" },
    { name: "Symmetra", image: "https://ui-avatars.com/api/?name=Symmetra&background=random" },
    { name: "Torbjorn", image: "https://ui-avatars.com/api/?name=Torbjorn&background=random" },
    { name: "Tracer", image: "https://ui-avatars.com/api/?name=Tracer&background=random" },
  ],
  "Dota 2": [
    { name: "Abaddon", image: "https://ui-avatars.com/api/?name=Abaddon&background=random" },
    { name: "Alchemist", image: "https://ui-avatars.com/api/?name=Alchemist&background=random" },
    { name: "Ancient Apparition", image: "https://ui-avatars.com/api/?name=Ancient%20Apparition&background=random" },
    { name: "Anti-Mage", image: "https://ui-avatars.com/api/?name=Anti-Mage&background=random" },
    { name: "Arc Warden", image: "https://ui-avatars.com/api/?name=Arc%20Warden&background=random" },
    { name: "Axe", image: "https://ui-avatars.com/api/?name=Axe&background=random" },
    { name: "Bane", image: "https://ui-avatars.com/api/?name=Bane&background=random" },
    { name: "Batrider", image: "https://ui-avatars.com/api/?name=Batrider&background=random" },
    { name: "Beastmaster", image: "https://ui-avatars.com/api/?name=Beastmaster&background=random" },
    { name: "Bloodseeker", image: "https://ui-avatars.com/api/?name=Bloodseeker&background=random" },
    { name: "Bounty Hunter", image: "https://ui-avatars.com/api/?name=Bounty%20Hunter&background=random" },
    { name: "Brewmaster", image: "https://ui-avatars.com/api/?name=Brewmaster&background=random" },
    { name: "Bristleback", image: "https://ui-avatars.com/api/?name=Bristleback&background=random" },
    { name: "Broodmother", image: "https://ui-avatars.com/api/?name=Broodmother&background=random" },
    { name: "Centaur Warrunner", image: "https://ui-avatars.com/api/?name=Centaur%20Warrunner&background=random" },
    { name: "Chaos Knight", image: "https://ui-avatars.com/api/?name=Chaos%20Knight&background=random" },
    { name: "Chen", image: "https://ui-avatars.com/api/?name=Chen&background=random" },
    { name: "Clinkz", image: "https://ui-avatars.com/api/?name=Clinkz&background=random" },
    { name: "Clockwerk", image: "https://ui-avatars.com/api/?name=Clockwerk&background=random" },
    { name: "Crystal Maiden", image: "https://ui-avatars.com/api/?name=Crystal%20Maiden&background=random" },
    { name: "Dark Seer", image: "https://ui-avatars.com/api/?name=Dark%20Seer&background=random" },
    { name: "Dazzle", image: "https://ui-avatars.com/api/?name=Dazzle&background=random" },
    { name: "Death Prophet", image: "https://ui-avatars.com/api/?name=Death%20Prophet&background=random" },
    { name: "Disruptor", image: "https://ui-avatars.com/api/?name=Disruptor&background=random" },
    { name: "Doom", image: "https://ui-avatars.com/api/?name=Doom&background=random" },
    { name: "Dragon Knight", image: "https://ui-avatars.com/api/?name=Dragon%20Knight&background=random" },
    { name: "Drow Ranger", image: "https://ui-avatars.com/api/?name=Drow%20Ranger&background=random" },
    { name: "Earth Spirit", image: "https://ui-avatars.com/api/?name=Earth%20Spirit&background=random" },
  ],
};
